const seed = {
  products: [
    { id: 1, name: 'AeroFlex Running Shoes', sku: 'AF-RUN-042', category: 'Footwear', price: 129, stock: 8, status: 'Active' },
    { id: 2, name: 'Core Daily Backpack', sku: 'CD-BAG-018', category: 'Accessories', price: 74, stock: 23, status: 'Active' },
    { id: 3, name: 'Northstar Field Watch', sku: 'NF-WAT-006', category: 'Accessories', price: 189, stock: 3, status: 'Active' },
    { id: 4, name: 'Meridian Knit Hoodie', sku: 'MK-HOD-033', category: 'Apparel', price: 96, stock: 0, status: 'Out of stock' },
    { id: 5, name: 'Studio Ceramic Bottle', sku: 'SC-BOT-021', category: 'Lifestyle', price: 42, stock: 16, status: 'Active' }
  ],
  customers: [
    { id: 1, name: 'Maya Chen', phone: '+1 415 555 0192', email: 'maya.chen@example.com', address: 'San Francisco, CA' },
    { id: 2, name: 'Jon Bell', phone: '+1 212 555 0181', email: 'jon.bell@example.com', address: 'Brooklyn, NY' },
    { id: 3, name: 'Elena Rossi', phone: '+39 02 555 0118', email: 'elena.rossi@example.com', address: 'Milan, Italy' },
    { id: 4, name: 'Samir Patel', phone: '+44 20 5550 1452', email: 'samir.patel@example.com', address: 'London, UK' }
  ],
  orders: [
    { id: 'ORD-1048', customerId: 1, items: [{ productId: 2, qty: 2, price: 74 }], total: 148, status: 'Paid', date: '2026-09-29' },
    { id: 'ORD-1047', customerId: 3, items: [{ productId: 1, qty: 1, price: 129 }, { productId: 5, qty: 1, price: 42 }], total: 171, status: 'Paid', date: '2026-09-28' },
    { id: 'ORD-1046', customerId: 2, items: [{ productId: 3, qty: 1, price: 189 }], total: 189, status: 'Pending', date: '2026-09-27' },
    { id: 'ORD-1045', customerId: 4, items: [{ productId: 5, qty: 3, price: 42 }], total: 126, status: 'Cancelled', date: '2026-09-26' }
  ]
};
const clone = value => JSON.parse(JSON.stringify(value));
let store = JSON.parse(localStorage.getItem('northstar-data') || 'null') || clone(seed);
let session = localStorage.getItem('northstar-session') || '';
let activePage = 'Dashboard';
let searchTerm = '';
let modal = null;
let toastTimer;
const app = document.querySelector('#app');
const money = value => `$${Number(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const save = () => localStorage.setItem('northstar-data', JSON.stringify(store));
const customerName = id => store.customers.find(item => item.id === id)?.name || 'Unknown customer';
const productName = id => store.products.find(item => item.id === id)?.name || 'Unknown product';
const icon = (symbol) => `<span class="nav-icon">${symbol}</span>`;
function showToast(message) { clearTimeout(toastTimer); const node = document.createElement('div'); node.className = 'toast'; node.textContent = message; document.body.append(node); toastTimer = setTimeout(() => node.remove(), 2800); }
function persistAndRender() { save(); render(); }

function render() { session ? renderApp() : renderLogin(); }
function renderLogin() { app.innerHTML = `<main class="login-shell"><section class="login-art"><div class="brand"><span class="brand-mark">N</span> northstar</div><h1>Make every order feel effortless.</h1><p>A focused operations workspace for teams who care about accurate stock, quick fulfillment, and a clear view of the business.</p></section><section class="login-panel"><form class="login-card" id="login-form"><div class="eyebrow">Operations console</div><h2>Welcome back</h2><p class="subtle">Sign in to manage your order workspace.</p><div class="field"><label for="email">Work email</label><input id="email" type="email" value="admin@northstar.test" required /></div><div class="field"><label for="password">Password</label><input id="password" type="password" value="password" required /></div><div id="login-error"></div><button class="btn btn-primary" type="submit">Sign in to workspace</button><div class="demo-note"><strong>Demo access</strong><br />Admin: admin@northstar.test / password<br />Staff: staff@northstar.test / password</div></form></section></main>`; document.querySelector('#login-form').addEventListener('submit', event => { event.preventDefault(); const email = document.querySelector('#email').value.trim(); if (!email.endsWith('@northstar.test')) { document.querySelector('#login-error').innerHTML = '<p class="subtle" style="color:#c64e59">Use one of the demo workspace accounts.</p>'; return; } session = email.startsWith('staff') ? 'Staff' : 'Admin'; localStorage.setItem('northstar-session', session); render(); }); }

function renderApp() { const nav = [['Dashboard','⌂'],['Orders','↗'],['Products','▦'],['Customers','◎']]; app.innerHTML = `<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">N</span> northstar</div><div class="workspace"><small>Workspace</small><strong>Northstar Supply Co.</strong></div><div class="nav-label">Manage</div><nav class="nav">${nav.map(([label,symbol]) => `<button class="${activePage === label ? 'active' : ''}" data-page="${label}">${icon(symbol)}${label}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="profile"><span class="avatar">${session === 'Admin' ? 'AM' : 'ST'}</span><div><strong>${session} account</strong><small>${session === 'Admin' ? 'Full access' : 'Order access'}</small></div></div><button class="nav" style="width:100%"><span></span></button></div></aside><main class="main"><header class="topbar"><div class="crumb">Workspace <span>/</span> <strong>${activePage}</strong></div><div class="top-actions"><span class="status"><i class="dot"></i> API connected</span><button class="btn btn-light" id="logout">Log out</button></div></header><section class="content">${pageContent()}</section></main></div>${modal || ''}`; document.querySelectorAll('[data-page]').forEach(button => button.addEventListener('click', () => { activePage = button.dataset.page; searchTerm = ''; render(); })); document.querySelector('#logout').addEventListener('click', () => { session = ''; localStorage.removeItem('northstar-session'); render(); }); bindPageEvents(); }
function pageContent() { if (activePage === 'Dashboard') return dashboard(); if (activePage === 'Products') return resourcePage('Products'); if (activePage === 'Customers') return resourcePage('Customers'); return ordersPage(); }
function dashboard() { const sales = store.orders.filter(order => order.status !== 'Cancelled').reduce((sum, order) => sum + order.total, 0); const low = store.products.filter(product => product.stock < 5); return `<div class="page-head"><div><div class="eyebrow">Tuesday, September 30, 2026</div><h1>Good morning, ${session === 'Admin' ? 'admin' : 'team'}.</h1><p class="subtle">Here is the pulse of your operation today.</p></div><div class="actions"><button class="btn btn-primary" id="new-order">+ New order</button></div></div><div class="stats"><div class="stat"><div class="stat-top">Customers <span class="stat-icon">◎</span></div><div class="stat-value">${store.customers.length}</div><div class="stat-meta">+12.4% this month</div></div><div class="stat"><div class="stat-top">Products <span class="stat-icon">▦</span></div><div class="stat-value">${store.products.length}</div><div class="stat-meta">${low.length} need attention</div></div><div class="stat"><div class="stat-top">Orders <span class="stat-icon">↗</span></div><div class="stat-value">${store.orders.length}</div><div class="stat-meta">+8.7% this month</div></div><div class="stat"><div class="stat-top">Total sales <span class="stat-icon">$</span></div><div class="stat-value">${money(sales)}</div><div class="stat-meta">+18.2% this month</div></div><div class="stat"><div class="stat-top">Low stock <span class="stat-icon" style="background:#fff5df;color:#ba780c">!</span></div><div class="stat-value">${low.length}</div><div class="stat-meta" style="color:#ba780c">Review inventory</div></div></div><div class="grid-2"><section class="panel"><div class="panel-head"><h3>Sales overview</h3><span>Last 7 days · USD</span></div><div class="chart"><div class="bars">${[42,64,52,76,58,88,70].map((height,index) => `<div class="bar-wrap"><i class="bar ${index === 5 ? 'hot' : ''}" style="height:${height}%"></i><i class="bar" style="height:${Math.max(20,height - 25)}%"></i></div>`).join('')}</div><div class="bar-labels">${['24 Sep','25 Sep','26 Sep','27 Sep','28 Sep','29 Sep','Today'].map(day => `<span>${day}</span>`).join('')}</div></div></section><section class="panel"><div class="panel-head"><h3>Inventory watchlist</h3><span>${low.length} items</span></div><div class="stock-list">${low.length ? low.map(product => `<div class="stock-item"><div><div class="product-name">${product.name}</div><div class="product-sku mono">${product.sku}</div></div><span class="pill low">${product.stock === 0 ? 'Out of stock' : `${product.stock} left`}</span></div>`).join('') : '<div class="empty">Inventory looks healthy.</div>'}</div></section></div>${recentOrders()}`; }
function recentOrders() { return `<section class="panel table-panel"><div class="panel-head"><h3>Recent orders</h3><button class="text-link" id="view-orders">View all →</button></div>${orderTable(store.orders.slice(0,4))}</section>`; }
function orderTable(orders) { if (!orders.length) return '<div class="empty">No orders found.</div>'; return `<table><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Total</th><th>Status</th></tr></thead><tbody>${orders.map(order => `<tr><td><strong class="mono">${order.id}</strong></td><td>${customerName(order.customerId)}</td><td class="mono">${order.date}</td><td><strong>${money(order.total)}</strong></td><td><span class="pill ${order.status.toLowerCase()}">${order.status}</span></td></tr>`).join('')}</tbody></table>`; }
function ordersPage() { const filtered = store.orders.filter(order => `${order.id} ${customerName(order.customerId)}`.toLowerCase().includes(searchTerm.toLowerCase())); return `<div class="page-head"><div><div class="eyebrow">Order management</div><h1>Orders</h1><p class="subtle">Track fulfillment and keep every sale accountable.</p></div><div class="actions"><button class="btn btn-primary" id="new-order">+ New order</button></div></div><section class="panel table-panel" style="margin-top:0"><div class="panel-head"><h3>All orders <span>· ${filtered.length} records</span></h3><div class="table-tools"><input class="search" id="table-search" placeholder="Search orders..." value="${searchTerm}" /></div></div>${orderTable(filtered)}</section>`; }
function resourcePage(type) { const isProducts = type === 'Products'; const records = (isProducts ? store.products : store.customers).filter(item => `${item.name} ${item.email || ''} ${item.sku || ''}`.toLowerCase().includes(searchTerm.toLowerCase())); return `<div class="page-head"><div><div class="eyebrow">Catalog & relationships</div><h1>${type}</h1><p class="subtle">${isProducts ? 'Keep pricing and inventory ready for the next order.' : 'Know exactly who your team is serving.'}</p></div><div class="actions"><button class="btn btn-primary" id="add-record">+ Add ${isProducts ? 'product' : 'customer'}</button></div></div><section class="panel table-panel" style="margin-top:0"><div class="panel-head"><h3>${type} <span>· ${records.length} records</span></h3><div class="table-tools"><input class="search" id="table-search" placeholder="Search ${type.toLowerCase()}..." value="${searchTerm}" /></div></div>${isProducts ? productTable(records) : customerTable(records)}</section>`; }
function productTable(records) { if (!records.length) return '<div class="empty">No products found.</div>'; return `<table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th></th></tr></thead><tbody>${records.map(product => `<tr><td><strong>${product.name}</strong><div class="product-sku mono">${product.sku}</div></td><td>${product.category}</td><td>${money(product.price)}</td><td><strong>${product.stock}</strong></td><td><span class="pill ${product.stock < 5 ? 'low' : 'ok'}">${product.stock < 5 ? (product.stock ? 'Low stock' : 'Out of stock') : product.status}</span></td><td>${session === 'Admin' ? `<button class="text-link delete-product" data-id="${product.id}">Delete</button>` : ''}</td></tr>`).join('')}</tbody></table>`; }
function customerTable(records) { if (!records.length) return '<div class="empty">No customers found.</div>'; return `<table><thead><tr><th>Customer</th><th>Phone</th><th>Email</th><th>Location</th></tr></thead><tbody>${records.map(customer => `<tr><td><strong>${customer.name}</strong></td><td class="mono">${customer.phone}</td><td>${customer.email}</td><td>${customer.address}</td></tr>`).join('')}</tbody></table>`; }
function newOrderModal() { modal = `<div class="modal-backdrop"><form class="modal" id="order-form"><div class="modal-head"><h2>Create order</h2><button type="button" class="close" id="close-modal">×</button></div><div class="modal-body"><div class="field" style="margin-top:0"><label>Customer</label><select id="order-customer" required><option value="">Choose a customer...</option>${store.customers.map(customer => `<option value="${customer.id}">${customer.name} · ${customer.email}</option>`).join('')}</select></div><div style="margin-top:24px"><label class="eyebrow" style="font-size:10px">Order items</label><div id="order-lines"><div class="order-line"><div class="field" style="margin-top:0"><label>Product</label><select class="line-product" required><option value="">Choose a product...</option>${store.products.filter(product => product.stock > 0).map(product => `<option value="${product.id}">${product.name} · ${product.stock} in stock</option>`).join('')}</select></div><div class="field" style="margin-top:0"><label>Quantity</label><input class="line-qty" type="number" min="1" value="1" required /></div><div class="field" style="margin-top:0"><label>Unit price</label><input class="line-price" value="$0.00" readonly /></div><button type="button" class="remove-line" disabled>×</button></div></div><button type="button" class="text-link" id="add-line" style="margin-top:14px">+ Add another item</button></div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:25px;padding-top:18px;border-top:1px solid var(--line)"><span class="subtle">Server-calculated total</span><strong id="order-total" style="font-size:23px;letter-spacing:-.05em">$0.00</strong></div></div><div class="modal-foot"><button type="button" class="btn btn-light" id="cancel-modal">Cancel</button><button class="btn btn-primary" type="submit">Place order</button></div></form></div>`; render(); }
function bindOrderModal() { document.querySelector('#close-modal').addEventListener('click', () => { modal = null; render(); }); document.querySelector('#cancel-modal').addEventListener('click', () => { modal = null; render(); }); const lines = () => [...document.querySelectorAll('.order-line')]; const update = () => { let total = 0; lines().forEach(line => { const product = store.products.find(item => item.id === Number(line.querySelector('.line-product').value)); const quantity = Number(line.querySelector('.line-qty').value) || 0; line.querySelector('.line-price').value = product ? money(product.price) : '$0.00'; total += product ? product.price * quantity : 0; }); document.querySelector('#order-total').textContent = money(total); }; document.querySelector('#add-line').addEventListener('click', () => { const template = document.querySelector('.order-line').cloneNode(true); template.querySelector('.line-product').value = ''; template.querySelector('.line-qty').value = '1'; template.querySelector('.line-price').value = '$0.00'; template.querySelector('.remove-line').disabled = false; document.querySelector('#order-lines').append(template); template.querySelector('.remove-line').addEventListener('click', () => { template.remove(); update(); }); template.querySelector('.line-product').addEventListener('change', update); template.querySelector('.line-qty').addEventListener('input', update); }); document.querySelectorAll('.line-product,.line-qty').forEach(input => input.addEventListener(input.classList.contains('line-qty') ? 'input' : 'change', update)); document.querySelector('#order-form').addEventListener('submit', event => { event.preventDefault(); const customerId = Number(document.querySelector('#order-customer').value); const items = lines().map(line => ({ productId: Number(line.querySelector('.line-product').value), qty: Number(line.querySelector('.line-qty').value) })).filter(item => item.productId); if (!customerId || !items.length) return showToast('Choose a customer and at least one product.'); for (const item of items) { const product = store.products.find(entry => entry.id === item.productId); if (!product || item.qty < 1 || item.qty > product.stock) return showToast(`${product?.name || 'Product'} does not have enough stock.`); } let total = 0; items.forEach(item => { const product = store.products.find(entry => entry.id === item.productId); product.stock -= item.qty; total += product.price * item.qty; product.status = product.stock ? 'Active' : 'Out of stock'; }); store.orders.unshift({ id: `ORD-${1049 + store.orders.length}`, customerId, items: items.map(item => ({ ...item, price: store.products.find(product => product.id === item.productId).price })), total, status: 'Paid', date: '2026-09-30' }); modal = null; persistAndRender(); showToast('Order placed and inventory updated.'); }); update(); }
function bindPageEvents() { const search = document.querySelector('#table-search'); if (search) search.addEventListener('input', event => { searchTerm = event.target.value; const cursor = event.target.selectionStart; render(); const next = document.querySelector('#table-search'); next.focus(); next.setSelectionRange(cursor, cursor); }); const newOrder = document.querySelector('#new-order'); if (newOrder) newOrder.addEventListener('click', newOrderModal); const viewOrders = document.querySelector('#view-orders'); if (viewOrders) viewOrders.addEventListener('click', () => { activePage = 'Orders'; render(); }); const addRecord = document.querySelector('#add-record'); if (addRecord) addRecord.addEventListener('click', () => showToast('This demo keeps the focus on order operations. Connect the Laravel CRUD endpoint to enable this form.')); document.querySelectorAll('.delete-product').forEach(button => button.addEventListener('click', () => { if (confirm('Delete this product?')) { store.products = store.products.filter(product => product.id !== Number(button.dataset.id)); persistAndRender(); showToast('Product deleted.'); } })); if (modal) bindOrderModal(); }
render();